language: java
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IN2QR6AN/D6mwKz/uueCmTYgAsPXCsH7qnB1ExYlJ7a7lIvUWcTk/YC4Kg7IuPXXf/7yXjVZLx7ce9Ecu/1tUrLbobrPlZgdOP4zWb52kEQizZW9q3KFcq2hnbD9weBAwOvqKnghGxMtBr2UGSH+T8H9P/9V2HSlr54HFmBpSE5qEM8+G6wdqpFulAHxf7al38oAc2qkkh2Yw2sMag3sNt0MlSZL3EOvtbLbP1x2AAzr6dn248+ly8q1uCkxzNyuW40dI0hrHv/DhbEHVAwOdXIVE7hVJixJt9jsYLowq0N7zsHDWvjwVfQpLoUqc0uNR3iqMlWe3XOYgjoIqOTDeZEpjenbbL9OLfH53oUwbtl5qnOwOfKoNlJ2GjpGc6EnHhVvHeJezJmrayBUnt8ivBu7fEPCNr4FF/t3MTC+FDsc6ssgTK2bNiXVLlnHJJoQVqP3udZkDMJrSjutvv7js4qdnKbeSNfOR1KuxpoV9dF6J5H4xzvxFKJeIOy1UwbBeLem5PEwCXbBQ8Df9XAiBf/IOedAo5iS+ISAXQAWllKSOzgenV819z+0kmCqu+OUjzcE5zqMCXO8YP+fjvLM2R2G2BELBUA68eUum6HYVW4ITgldEj1ZwfaC3772IAE/juSYvd+rdJuwAb2BjWIz1w0DTC9zrs2B/HLnEHssLi0="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "yeazj/bankwebapp"
      description: "<Your project description here>"
    notification_email: yeazjaddoo@hotmail.com
    build_command_prepend: "<Your build preprocessing command here>"
    build_command: "<Your build command here>"
    branch_pattern: coverity_scan